import { Trait } from '@/types'
import {
  Coffee, PawPrint, Moon, Sunrise, BatteryLow,
  Smile, Brain, Heart, Pizza, Mic2,
  Home, Users, MessageCircle, Meh, ShieldCheck,
  Code2, Smartphone, Laugh, Share2, Tv2,
  UtensilsCrossed, PartyPopper, Gamepad2, PhoneOff, Music2,
  Sparkles, Flame, Trophy, Dumbbell, Briefcase,
  Car, Shirt, Crown, PenOff, BadgeCheck,
  HandHeart, Radio, ChefHat, Clock, Headphones,
} from 'lucide-react'

// Colors follow a Latin-square shift per row so no column is monotone
export const TRAITS: Trait[] = [
  { key: 'coffee_addict',       label: 'Coffee addict',               icon: Coffee,           color: 'green'  },
  { key: 'dog_person',          label: 'Dog person',                  icon: PawPrint,         color: 'violet' },
  { key: 'night_owl',           label: 'Night owl',                   icon: Moon,             color: 'rose'   },
  { key: 'early_bird',          label: 'Early bird',                  icon: Sunrise,          color: 'amber'  },
  { key: 'always_tired',        label: 'Always tired',                icon: BatteryLow,       color: 'sky'    },
  { key: 'chill_pressure',      label: 'Chill under pressure',        icon: Smile,            color: 'violet' },
  { key: 'overthinks',          label: 'Overthinks everything',       icon: Brain,            color: 'rose'   },
  { key: 'big_hugger',          label: 'Big hugger',                  icon: Heart,            color: 'amber'  },
  { key: 'junk_food',           label: 'Junk food lover',             icon: Pizza,            color: 'sky'    },
  { key: 'sings_shower',        label: 'Sings in the shower',         icon: Mic2,             color: 'green'  },
  { key: 'introvert',           label: 'Introvert until comfortable', icon: Home,             color: 'rose'   },
  { key: 'extrovert',           label: 'Extrovert everywhere',        icon: Users,            color: 'amber'  },
  { key: 'group_chat_talker',   label: 'Group chat over-talker',      icon: MessageCircle,    color: 'sky'    },
  { key: 'gets_bored',          label: 'Gets bored easily',           icon: Meh,              color: 'green'  },
  { key: 'hard_to_offend',      label: 'Hard to offend',              icon: ShieldCheck,      color: 'violet' },
  { key: 'tech_nerd',           label: 'Tech nerd',                   icon: Code2,            color: 'amber'  },
  { key: 'always_on_phone',     label: 'Always on phone',             icon: Smartphone,       color: 'sky'    },
  { key: 'meme_dealer',         label: 'Certified meme dealer',       icon: Laugh,            color: 'green'  },
  { key: 'social_media',        label: 'Social media addict',         icon: Share2,           color: 'violet' },
  { key: 'netflix_junkie',      label: 'Netflix junkie',              icon: Tv2,              color: 'rose'   },
  { key: 'always_hungry',       label: 'Always hungry',               icon: UtensilsCrossed,  color: 'sky'    },
  { key: 'class_clown',         label: 'Class clown',                 icon: PartyPopper,      color: 'green'  },
  { key: 'video_games',         label: 'Video Games Please',          icon: Gamepad2,         color: 'violet' },
  { key: 'dont_call_text',      label: "Don't call, just text",       icon: PhoneOff,         color: 'rose'   },
  { key: 'can_dance',           label: 'Can dance for Africa',        icon: Music2,           color: 'amber'  },
  { key: 'life_of_party',       label: 'Life of the party',           icon: Sparkles,         color: 'green'  },
  { key: 'naughty_by_nature',   label: 'Naughty by nature',           icon: Flame,            color: 'violet' },
  { key: 'sports_maniac',       label: 'Sports maniac',               icon: Trophy,           color: 'rose'   },
  { key: 'gym_rat',             label: 'Gym rat',                     icon: Dumbbell,         color: 'amber'  },
  { key: 'always_serious',      label: 'Always serious',              icon: Briefcase,        color: 'sky'    },
  { key: 'manic_driver',        label: 'Manic driver',                icon: Car,              color: 'violet' },
  { key: 'fashionista',         label: 'Fashionista',                 icon: Shirt,            color: 'rose'   },
  { key: 'born_leader',         label: 'Born leader',                 icon: Crown,            color: 'amber'  },
  { key: 'never_has_biro',      label: 'Never has a biro',            icon: PenOff,           color: 'sky'    },
  { key: 'calls_chief',         label: "Calls everyone 'chief'",      icon: BadgeCheck,       color: 'green'  },
  { key: 'prayer_warrior',      label: 'Prayer warrior',              icon: HandHeart,        color: 'rose'   },
  { key: 'can_talk_africa',     label: 'Can talk for Africa',         icon: Radio,            color: 'amber'  },
  { key: 'top_chef',            label: 'Top Chef',                    icon: ChefHat,          color: 'sky'    },
  { key: 'workaholic',          label: 'Workaholic',                  icon: Clock,            color: 'green'  },
  { key: 'always_on_earphones', label: 'Always on earphones',         icon: Headphones,       color: 'violet' },
]

export const TRAIT_MAP = new Map(TRAITS.map(t => [t.key, t.label]))
