import { Trait } from '@/types'
import {
  Coffee, PawPrint, Moon, Sunrise, BatteryLow,
  Smile, Brain, Heart, Pizza, Mic2,
  Home, Users, MessageCircle, Meh, ShieldCheck,
  Code2, Smartphone, Laugh, Share2, Tv2,
  UtensilsCrossed, PartyPopper, Gamepad2, PhoneOff, Music2,
  Sparkles, Flame, Trophy, Dumbbell, Briefcase,
  Car, Shirt, Crown, PenOff, BadgeCheck,
  HandHeart, Radio, ChefHat, Clock, Headphones,
} from 'lucide-react'

export const TRAITS: Trait[] = [
  { key: 'coffee_addict',       label: 'Coffee addict',             icon: Coffee,           color: 'amber'  },
  { key: 'dog_person',          label: 'Dog person',                icon: PawPrint,         color: 'rose'   },
  { key: 'night_owl',           label: 'Night owl',                 icon: Moon,             color: 'violet' },
  { key: 'early_bird',          label: 'Early bird',                icon: Sunrise,          color: 'amber'  },
  { key: 'always_tired',        label: 'Always tired',              icon: BatteryLow,       color: 'sky'    },
  { key: 'chill_pressure',      label: 'Chill under pressure',      icon: Smile,            color: 'green'  },
  { key: 'overthinks',          label: 'Overthinks everything',     icon: Brain,            color: 'violet' },
  { key: 'big_hugger',          label: 'Big hugger',                icon: Heart,            color: 'rose'   },
  { key: 'junk_food',           label: 'Junk food lover',           icon: Pizza,            color: 'amber'  },
  { key: 'sings_shower',        label: 'Sings in the shower',       icon: Mic2,             color: 'sky'    },
  { key: 'introvert',           label: 'Introvert until comfortable', icon: Home,           color: 'green'  },
  { key: 'extrovert',           label: 'Extrovert everywhere',      icon: Users,            color: 'violet' },
  { key: 'group_chat_talker',   label: 'Group chat over-talker',    icon: MessageCircle,    color: 'rose'   },
  { key: 'gets_bored',          label: 'Gets bored easily',         icon: Meh,              color: 'amber'  },
  { key: 'hard_to_offend',      label: 'Hard to offend',            icon: ShieldCheck,      color: 'sky'    },
  { key: 'tech_nerd',           label: 'Tech nerd',                 icon: Code2,            color: 'green'  },
  { key: 'always_on_phone',     label: 'Always on phone',           icon: Smartphone,       color: 'violet' },
  { key: 'meme_dealer',         label: 'Certified meme dealer',     icon: Laugh,            color: 'rose'   },
  { key: 'social_media',        label: 'Social media addict',       icon: Share2,           color: 'amber'  },
  { key: 'netflix_junkie',      label: 'Netflix junkie',            icon: Tv2,              color: 'sky'    },
  { key: 'always_hungry',       label: 'Always hungry',             icon: UtensilsCrossed,  color: 'green'  },
  { key: 'class_clown',         label: 'Class clown',               icon: PartyPopper,      color: 'violet' },
  { key: 'video_games',         label: 'Video Games Please',        icon: Gamepad2,         color: 'rose'   },
  { key: 'dont_call_text',      label: "Don't call, just text",     icon: PhoneOff,         color: 'amber'  },
  { key: 'can_dance',           label: 'Can dance for Africa',      icon: Music2,           color: 'sky'    },
  { key: 'life_of_party',       label: 'Life of the party',         icon: Sparkles,         color: 'green'  },
  { key: 'naughty_by_nature',   label: 'Naughty by nature',         icon: Flame,            color: 'violet' },
  { key: 'sports_maniac',       label: 'Sports maniac',             icon: Trophy,           color: 'rose'   },
  { key: 'gym_rat',             label: 'Gym rat',                   icon: Dumbbell,         color: 'amber'  },
  { key: 'always_serious',      label: 'Always serious',            icon: Briefcase,        color: 'sky'    },
  { key: 'manic_driver',        label: 'Manic driver',              icon: Car,              color: 'green'  },
  { key: 'fashionista',         label: 'Fashionista',               icon: Shirt,            color: 'violet' },
  { key: 'born_leader',         label: 'Born leader',               icon: Crown,            color: 'rose'   },
  { key: 'never_has_biro',      label: 'Never has a biro',          icon: PenOff,           color: 'amber'  },
  { key: 'calls_chief',         label: "Calls everyone 'chief'",    icon: BadgeCheck,       color: 'sky'    },
  { key: 'prayer_warrior',      label: 'Prayer warrior',            icon: HandHeart,        color: 'green'  },
  { key: 'can_talk_africa',     label: 'Can talk for Africa',       icon: Radio,            color: 'violet' },
  { key: 'top_chef',            label: 'Top Chef',                  icon: ChefHat,          color: 'rose'   },
  { key: 'workaholic',          label: 'Workaholic',                icon: Clock,            color: 'amber'  },
  { key: 'always_on_earphones', label: 'Always on earphones',       icon: Headphones,       color: 'sky'    },
]

export const TRAIT_MAP = new Map(TRAITS.map(t => [t.key, t.label]))
